### ISSUE TITLE
Background subtraction failure

### ISSUE THREAD

**Issue by Shivangi1010** [jkrogager/PyNOT#22]
Hi,
Please let me know why after wavelength calibration, the background subtraction is failing?
I have checked the 

          - Plotting fitted arc line positions in 2D frame
 [OUTPUT] - Saving figure: spectra/QSO1644+263/al-gr4_slit1.8/ob1/PixTable2D.pdf
          - Interpolating input image onto rectified wavelength solution
 [ERROR]  - Wavelength array is not monotonic.
          - Check the parameters `fit_window` and `order_wl`.
FATAL ERROR
          - Running task: Background Subtraction
 [ERROR]  - Automatic background subtraction failed!
 !! FATAL ERROR !!
 Consult the log: spectra/QSO1644+263/al-gr4_slit1.8/ob1/pynot.log

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/home/shivangi/anaconda3/bin/pynot", line 33, in <module>
    sys.exit(load_entry_point('PyNOT-redux==1.3.3', 'console_scripts', 'pynot')())
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/main.py", line 594, in main
    run_pipeline(options_fname=args.params,
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/redux.py", line 427, in run_pipeline
    bg_msg = auto_fit_background(rect2d_fname, bgsub2d_fname, dispaxis=1,
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/scired.py", line 280, in auto_fit_background
    data = fits.getdata(data_fname)
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/convenience.py", line 221, in getdata
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/convenience.py", line 1125, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 214, in fitsopen
    return HDUList.fromfile(
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 482, in fromfile
    return cls._readfrom(
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1170, in _readfrom
    fileobj = _File(
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/astropy/io/fits/file.py", line 636, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
FileNotFoundError: [Errno 2] No such file or directory: 'spectra/QSO1644+263/al-gr4_slit1.8/ob1/RECT2D_QSO1644+263.fits'

**Comment by jkrogager** [comment]
This is because the wavelength solution wasn't calculated correctly.

You get the following error:

[ERROR] - Wavelength array is not monotonic.
- Check the parameters fit_window and order_wl.
