### ISSUE TITLE
Extraction GUI fails

### ISSUE THREAD

**Issue by jkrogager** [jkrogager/PyNOT#23]
From Giorgos:

When I do manual extraction using the GUI, and I get to the point where I click on “fit spectral trace” the GUI crashes. Below I copy the full error message.
I notice on Github that the last comment 10 months ago associated with extract_gui.py is exactly: "Bugfix in plotting ‘is_last_row'
So maybe you know already what is wrong ?

```
         - Extraction: Starting Graphical User Interface
Traceback (most recent call last):
  File "/Users/giorgos/anaconda3/envs/pynot/lib/python3.12/site-packages/pynot/extract_gui.py", line 642, in <lambda>
    self.fit_btn1.clicked.connect(lambda x: self.fit_trace(force=True))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giorgos/anaconda3/envs/pynot/lib/python3.12/site-packages/pynot/extract_gui.py", line 1771, in fit_trace
    self.plot_fitted_points()
  File "/Users/giorgos/anaconda3/envs/pynot/lib/python3.12/site-packages/pynot/extract_gui.py", line 1859, in plot_fitted_points
    if not ax.is_last_row():
           ^^^^^^^^^^^^^^
AttributeError: 'Axes' object has no attribute 'is_last_row'
zsh: abort      pynot spex night1.yml --science

```

**Comment by jkrogager** [comment]
Fixed now by pull request #24 .
