### ISSUE TITLE
PyNOT v2.1.1 raises error on "No FITS header key: ESO DPR CATG"

### ISSUE THREAD

**Issue by sPaMFouR** [jkrogager/PyNOT#32]
Hi,

Upon running PyNOT v2.1.1 on NOT data from ALFOSC captured on 2024-10-31, I encounter the following error, Classifying files:
Traceback (most recent call last):

  File "/Users/avinash/Softwares/miniconda3/envs/pypeit/bin/pynot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pypeit/lib/python3.11/site-packages/pynot/main.py", line 595, in main
    initialize(args.path, args.mode, pfc_fname=args.output, pars_fname=args.pars, verbose=args.silent)
  File "/Users/avinash/Softwares/miniconda3/envs/pypeit/lib/python3.11/site-packages/pynot/main.py", line 103, in initialize
    database, message = do.classify(path, progress=verbose)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pypeit/lib/python3.11/site-packages/pynot/data/organizer.py", line 445, in classify
    ftype = classify_file(fname, rules)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pypeit/lib/python3.11/site-packages/pynot/data/organizer.py", line 293, in classify_file
    raise RuleCriterionError(key, cond)
pynot.data.organizer.RuleCriterionError: Error in condition: DPR.CATG == CALIB. No FITS header key: ESO DPR CATG

However, when I try to run PyNOT v1.3.4 on the dataset from NOT, I don't encounter this fatal error. 

Is the current version unable to capture and skip the error? Is this an essential part of the new version of the pipeline?

**Comment by jkrogager** [comment]
Hi, this is because the default instrument setting of PyNOT was set to EFOSC2. I have changed this in the latest version 2.1.2. Otherwise you can run the command `pynot use alfosc` from the terminal to switch back to ALFOSC.

**Comment by sPaMFouR** [comment]
Thanks for your inputs and for addressing this!
