### ISSUE TITLE
Calib and Std repositories not present in the git clone install of PyNOT v2.1.2

### ISSUE THREAD

**Issue by sPaMFouR** [jkrogager/PyNOT#33]
In the fresh installation of v2.1.2, the calibration and std data files didn't copy/install to Python executable folder of PyNOT, when I cloned the repo from GitHub and installed using "python setup.py install".  May be that's a bug that might be worth addressing.

This was after running : 

`pynot init spex 2024-11-24 --pars night1.yml`

Traceback (most recent call last):
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/bin/pynot", line 33, in <module>
    sys.exit(load_entry_point('PyNOT-redux==2.1.2', 'console_scripts', 'pynot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/bin/pynot", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/__init__.py", line 29, in <module>
    spec.loader.exec_module(instrument)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/alfosc.py", line 65, in <module>
    filter_table = Table.read(filter_table_fname, format='ascii.fixed_width')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/io/registry/core.py", line 221, in read
    data = reader(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/io/ascii/connect.py", line 19, in io_read
    return read(filename, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/io/ascii/ui.py", line 487, in read
    dat = reader.read(table)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/io/ascii/core.py", line 1424, in read
    self.lines = self.inputter.get_lines(table, newline=newline)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/io/ascii/core.py", line 336, in get_lines
    with get_readable_fileobj(table, encoding=self.encoding) as fileobj:
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/astropy/utils/data.py", line 365, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, "r")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/calib/alfosc_filters.dat'

**Comment by jkrogager** [comment]
Have you tried installing it using `pip install` instead?

**Comment by sPaMFouR** [comment]
pip install worked just fine. 

But the updated version 2.12 runs into a lot of errors. I still haven't been able to figure out how to get ALFOSC reduced on my M3 Pro Chipset.

-Works fine
pynot init spex 2024-11-24 --pars night1.yml

-Throws errors with NORM_SFLAT in interactive mode.
pynot spex --interactive night1.yml

Error goes as follows:
Initial match for MBIAS: ['spectra/MBIAS_500x2102.fits']
Initial match for NORM_SFLAT: []
No matches for NORM_SFLAT, ensure file metadata matches the criteria.
 [ERROR]  - No matches for NORM_SFLAT. File metadata may not match criteria.
Traceback (most recent call last):
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/bin/pynot", line 33, in <module>
    sys.exit(load_entry_point('PyNOT-redux==2.1.2', 'console_scripts', 'pynot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/main.py", line 604, in main
    run_pipeline(options_fname=args.params,
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/redux.py", line 218, in run_pipeline
    task_output, log = task_response(task_options, database, status, log=log, verbose=verbose, app=app,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/response.py", line 672, in task_response
    norm_flat = organizer.match_single_calib(raw_img, database, 'NORM_SFLAT', log, date=False,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/avinash/Softwares/miniconda3/envs/pynot/lib/python3.11/site-packages/PyNOT_redux-2.1.2-py3.11.egg/pynot/data/organizer.py", line 127, in match_single_calib
    raise KeyError(f"Could not match filetype {tag}")
KeyError: 'Could not match filetype NORM_SFLAT'

May be I shouldn't spam this error I run into here and take this up over Email!

**Comment by jkrogager** [comment]
It looks to me as if you don't have any spectroscopic flat field observations in the dataset. Could you please verify that you have all the necessary files for the full reduction?
