### ISSUE TITLE
Problems with flats in imaging mode

### ISSUE THREAD

**Issue by steveschulze** [jkrogager/PyNOT#9]
Hi JK,

I downloaded the latest version of your pipeline. When I try to reduce the imaging data, I get the following error.

 ```
[ERROR]  - Flat field combination failed for filter: i_SDSS
 !! FATAL ERROR !!
 Consult the log: pynot_30Mar2022-10h26m11.log

Unexpected error: <class 'TypeError'>
Traceback (most recent call last):
  File "/Volumes/Home/steve/opt/anaconda3/envs/pypeit/bin/pynot", line 33, in <module>
    sys.exit(load_entry_point('PyNOT-redux==1.0', 'console_scripts', 'pynot')())
  File "/Volumes/Home/steve/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/PyNOT_redux-1.0-py3.9.egg/pynot/main.py", line 760, in main
    run_pipeline(options_fname=args.params,
  File "/Volumes/Home/steve/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/PyNOT_redux-1.0-py3.9.egg/pynot/phot_redux.py", line 140, in run_pipeline
    _, flat_msg = combine_flat_frames(flat_frames, comb_flat_fname, mbias=master_bias_fname,
  File "/Volumes/Home/steve/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/PyNOT_redux-1.0-py3.9.egg/pynot/calibs.py", line 186, in combine_flat_frames
    msg.append("          - Getting dispersion axis from file: %i" % dispaxis)
TypeError: %i format: a number is required, not NoneType
```

I modified lines 186 in calibs.py and things work smoothly now.

`msg.append("          - Getting dispersion axis from file: {!s}".format(dispaxis))`

Cheers,

Steve

**Comment by jkrogager** [comment]
Should be fixed by latest merge #12. Otherwise let me know.
